@username = 
@password = 

# @name session
POST https://bsky.social/xrpc/com.atproto.server.createSession
content-type: application/json

{
    "identifier": "{{username}}.bsky.social",
    "password": "{{password}}"
}

@accessJwt = {{session.response.body.accessJwt}}

###

# makes a post on Jan 1, 1AD
POST https://bsky.social/xrpc/com.atproto.repo.createRecord
content-type: application/json
Authorization: Bearer {{accessJwt}}

{
    "repo": "{{username}}.bsky.social",
    "collection": "app.bsky.feed.post",
    "record": 
        {
            "text": "First",
            "createdAt": "0000-01-01T07:53:01Z"
        }
}
