@username = 
@password = 

# authentication
# @name session
POST https://bsky.social/xrpc/com.atproto.server.createSession
content-type: application/json

{
    "identifier": "{{username}}.bsky.social",
    "password": "{{password}}"
}

###

@accessJwt = {{session.response.body.accessJwt}}

###

# makes a post on Jan 1, 1AD
POST https://bsky.social/xrpc/com.atproto.repo.createRecord
content-type: application/json
Authorization: Bearer {{accessJwt}}

{
    "repo": "{{username}}.bsky.social",
    "collection": "app.bsky.feed.post",
    "record": {
        "text": "First",
        "createdAt": "0000-01-01T07:53:01Z",
        "langs": ["en-US"]
    }
}

###

# e.g. https://bsky.app/profile/sekhmet.bsky.social/post/3k7b6jatky222
@rkey = 3k7b6jatky222

# gets the uri and cid for a post
# @name get_uri_cid
GET https://bsky.social/xrpc/com.atproto.repo.getRecord
    ?repo={{username}}.bsky.social
    &collection=app.bsky.feed.post
    &rkey={{rkey}}

###

@text = If you're curious - https://github.com/Skhmt/bsky_tests
@link_byte_start = 20
@link_byte_end = 55
@link_uri = https://github.com/Skhmt/bsky_tests

@uri = {{get_uri_cid.response.body.uri}}
@cid = {{get_uri_cid.response.body.cid}}

# replies at the top level to the post from the previous GET with @text
POST https://bsky.social/xrpc/com.atproto.repo.createRecord
content-type: application/json
Authorization: Bearer {{accessJwt}}

{
    "repo": "{{username}}.bsky.social",
    "collection": "app.bsky.feed.post",
    "record": {
        "text": "{{text}}",
        "createdAt": "0000-01-01T07:54:01Z",
        "langs": ["en-US"],
        "reply": {
            "root": {
                "uri": "{{uri}}",
                "cid": "{{cid}}"
            },
            "parent": {
                "uri": "{{uri}}",
                "cid": "{{cid}}"
            }
        },
        "facets": [
            {
                "index": {
                    "byteStart": {{link_byte_start}},
                    "byteEnd": {{link_byte_end}}
                },
                "features": [
                    {
                        "$type": "app.bsky.richtext.facet#link",
                        "uri": "{{link_uri}}"
                    }
                ]
            }
        ]
    }
}
